"use client";

import React, { useEffect, useState } from "react";
import { useSession } from "next-auth/react";
import { ShieldAlert, ShieldCheck, CheckCircle2, XCircle, Clock, Search, MessageSquarePlus } from "lucide-react";
import { getPendingApprovals, resolveApproval } from "@/app/actions/approval";
import toast from "react-hot-toast";

export default function ApprovalsDeskPage() {
  const { data: session } = useSession();
  const [requests, setRequests] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [resolvingId, setResolvingId] = useState<string | null>(null);
  const [notesText, setNotesText] = useState<Record<string, string>>({});

  useEffect(() => {
    loadApprovals();
  }, []);

  const loadApprovals = async () => {
    try {
      const data = await getPendingApprovals();
      setRequests(data);
    } catch (err) {
      toast.error("Failed to load approval requests.");
    } finally {
      setLoading(false);
    }
  };

  if (!session || session.user.role !== "RESIDENT") {
    return (
      <div className="p-6 text-center text-xs text-text-muted glass-panel rounded-2xl">
        Security warning: Access restricted to Greenwood Residents only.
      </div>
    );
  }

  const handleAction = async (approvalId: string, status: "APPROVED" | "REJECTED") => {
    setResolvingId(approvalId);
    const notes = notesText[approvalId] || "";
    const toastId = toast.loading(`Submitting ${status.toLowerCase()} response...`);
    
    try {
      const result = await resolveApproval(approvalId, status, notes);
      if (result.error) {
        toast.error(result.error, { id: toastId });
      } else {
        toast.success(result.message, { id: toastId });
        // Remove from list
        setRequests(prev => prev.filter(r => r.id !== approvalId));
      }
    } catch (err) {
      toast.error("Connection failure.", { id: toastId });
    } finally {
      setResolvingId(null);
    }
  };

  const handleNotesChange = (id: string, text: string) => {
    setNotesText(prev => ({ ...prev, [id]: text }));
  };

  return (
    <div className="space-y-6">
      
      {/* Page Title */}
      <div>
        <h2 className="font-heading font-bold text-2xl text-text-primary">Gate Approval Desk</h2>
        <p className="text-xs text-text-secondary">Authorise or block visitor check-in requests generated by the checkpoint guards</p>
      </div>

      {loading ? (
        <div className="space-y-4">
          <div className="h-20 w-full glass-panel rounded-2xl animate-pulse" />
          <div className="h-20 w-full glass-panel rounded-2xl animate-pulse" />
        </div>
      ) : requests.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {requests.map((req) => (
            <div key={req.id} className="p-6 rounded-2xl glass-panel-heavy space-y-6 border border-amber-500/10 bg-amber-500/5 relative overflow-hidden flex flex-col justify-between">
              
              {/* Request metadata header */}
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="inline-flex items-center space-x-1.5 px-2.5 py-1 rounded bg-amber-500/10 text-amber-500 text-[10px] font-semibold uppercase tracking-wider animate-pulse">
                    <Clock className="w-3.5 h-3.5" />
                    <span>Awaiting Decision</span>
                  </span>
                  <span className="text-[10px] text-text-muted font-mono">
                    {new Date(req.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </span>
                </div>
                
                <hr className="border-border/30" />
                
                {/* Visitor credentials */}
                <div className="space-y-2">
                  <h3 className="font-heading font-bold text-lg text-white">{req.log.visitor.name}</h3>
                  <p className="text-xs text-slate-300">Phone: {req.log.visitor.phone}</p>
                  <p className="text-xs text-slate-400">Purpose: <strong className="text-white">{req.log.purpose}</strong></p>
                  {req.log.vehicleNumber && <p className="text-xs text-slate-400 font-mono">Vehicle: {req.log.vehicleNumber}</p>}
                </div>
              </div>

              {/* Action input panel */}
              <div className="space-y-4 mt-6">
                <div>
                  <label className="block text-[10px] font-bold text-slate-400 mb-1.5 uppercase tracking-widest flex items-center space-x-1">
                    <MessageSquarePlus className="w-3.5 h-3.5 text-indigo-400" />
                    <span>Resident Response Note (Optional)</span>
                  </label>
                  <input
                    type="text"
                    value={notesText[req.id] || ""}
                    onChange={(e) => handleNotesChange(req.id, e.target.value)}
                    placeholder="e.g. Leave package at lobby door, please verify ID"
                    className="w-full h-10 px-3.5 rounded-xl border border-white/10 bg-slate-950/40 text-xs text-white placeholder-slate-600 focus:outline-none focus:border-indigo-500 transition-colors"
                  />
                </div>

                {/* Approve Reject buttons */}
                <div className="flex items-center space-x-3">
                  <button
                    onClick={() => handleAction(req.id, "REJECTED")}
                    disabled={resolvingId !== null}
                    className="flex-1 h-10 rounded-xl border border-red-500/20 hover:bg-red-500/10 text-red-500 text-xs font-semibold transition-colors flex items-center justify-center space-x-1"
                  >
                    <XCircle className="w-4 h-4" />
                    <span>Reject entry</span>
                  </button>
                  <button
                    onClick={() => handleAction(req.id, "APPROVED")}
                    disabled={resolvingId !== null}
                    className="flex-1 h-10 rounded-xl bg-brand-emerald hover:bg-emerald-500 text-white text-xs font-semibold transition-colors flex items-center justify-center space-x-1 shadow-md shadow-emerald-500/10"
                  >
                    <ShieldCheck className="w-4 h-4" />
                    <span>Approve entry</span>
                  </button>
                </div>
              </div>

            </div>
          ))}
        </div>
      ) : (
        <div className="py-20 text-center text-xs text-text-muted glass-panel rounded-2xl flex flex-col items-center justify-center space-y-3">
          <CheckCircle2 className="w-12 h-12 text-brand-emerald/20" />
          <h3 className="font-heading font-bold text-white text-sm">All Clear!</h3>
          <span>No gate checkpoint requests are pending for your Flat.</span>
        </div>
      )}

    </div>
  );
}
